[package]
name = "zenread"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = "2.0.0-rc.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
