[package]
name = "zenread"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-fs = "2"
rand = "0.8.5"
scraper = "0.19.0"
reqwest = { version = "0.12.4", features = ["blocking"] }
anyhow = "1.0.82"

[features]
custom-protocol = ["tauri/custom-protocol"]
