[package]
name = "backend"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
actix-web = "4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
scraper = "0.19.0"
reqwest = { version = "0.12.4", features = ["blocking"] }
