[package]
name = "backend"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
actix-web = "4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
